version: "3.9"
services:
  comparator:
    build: .
    ports:
      - "3036:3036"
  
  mysql:
    image: "mysql"
    restart: always
    # environment:
    #   MYSQL_ROOT_PASSWORD: test1
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - './.mysql-data/db:/var/lib/mysql'